version: 0.2

phases:
	build:
		commands:
			- echo Starting Build Phase
			- mvn clean package
	post_build:
		commands:
			- echo Build Phase Completed
artifacts:
	files:
		- target/order-service.jar
	discard-paths: yes